input {
  udp {
    port => 5514
    type => "dsm_log"
    codec => "plain"
  }
}


filter {
  if [type] == "dsm_log" {
    grok {
      match => {
        "message" => "<%{INT:syslog_pri}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{HOSTNAME:hostname} %{DATA:program}: %{GREEDYDATA:msg}"
      }
    }

    grok {
      match => {
        "msg" => [
          "User \[%{WORD:user}\] from \[%{IP:src_ip}\] signed in to \[%{WORD:service}\] %{WORD:status} via \[%{WORD:auth_method}\]",
          "User \[%{WORD:user}\] from \[%{IP:src_ip}\] failed to sign in to \[%{WORD:service}\] via \[%{WORD:auth_method}\] due to %{GREEDYDATA:failure_reason}"
        ]
      }
    }

    date {
      match => ["syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss"]
      target => "dsm_time"
      timezone => "Asia/Ho_Chi_Minh"
    }

    mutate {
      add_field => { "log_source" => "DSM" }
    }
    if [status] == "successfully" {
      mutate { add_field => { "result" => "success" } }
    } 

    if [failure_reason] {
      mutate { add_field => { "result" => "failure" } }
    }

  }
}


output {
  elasticsearch {
    hosts => [""]
    #user => "logstash_internal"
    #password =>
    api_key => ":"
    cacert => ""
    #index => "dsm-logs-%{+YYYY.MM.dd}"
    #ilm_enabled => false
    #manage_template => false
    data_stream => true
    data_stream_type => "logs"
    data_stream_dataset => "dsm"
    data_stream_namespace => "default"
    
    ssl => true
  }

  stdout { codec => rubydebug }
}


