input {
  udp {
    port => 5514
    type => "dsm_log"
    codec => "plain"
  }
}

filter {
  if [type] == "dsm_log" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:msg}" }
      overwrite => ["message"]
    }


    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }

    mutate {
      add_field => { "service" => "DSM" }
    }
  }
}


output {
  elasticsearch {
    hosts => [""]
    #user => ""
    #password =>
    api_key => ":"
    cacert => ""
    index => "dsm-logs-%{+YYYY.MM.dd}"
    ilm_enabled => false
    manage_template => false
    ssl => true
  }

  stdout { codec => rubydebug }
}


