input {
  udp {
    port => 5514
    type => "dsm_log"
    codec => "plain"
  }
}


filter {
  if [type] == "dsm_log" {
    grok {
      match => {
        "message" => "<%{INT:syslog_pri}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{HOSTNAME:hostname} %{DATA:program}: %{GREEDYDATA:msg}"
      }
    }

    grok {
      match => {
        "msg" => [
          "User \[%{WORD:user}\] from \[%{IP:src_ip}\] signed in to \[%{WORD:service}\] %{WORD:status} via \[%{WORD:auth_method}\]",
          "User \[%{WORD:user}\] from \[%{IP:src_ip}\] failed to sign in to \[%{WORD:service}\] via \[%{WORD:auth_method}\] due to %{GREEDYDATA:failure_reason}"
        ]
      }
    }

    date {
      match => ["syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss"]
      target => "@timestamp"
      timezone => "Asia/Ho_Chi_Minh"
    }

    mutate {
      add_field => { "log_source" => "DSM" }
    }
  }
}


output {
  elasticsearch {
    hosts => [""]
    #user => ""
    #password =>
    api_key => ":"
    cacert => ""
    index => "dsm-logs-%{+YYYY.MM.dd}"
    ilm_enabled => false
    manage_template => false
    ssl => true
  }

  stdout { codec => rubydebug }
}


