input {
  file {
    #path => "/var/log/auth.log"        # Đường dẫn log cần đọc
	path => "/etc/logstash/dump/0_logs.txt"
    start_position => "beginning"      # Đọc từ đầu file (nếu để "end" thì chỉ đọc log mới ghi thêm)
    sincedb_path => "/dev/null"        # Bỏ qua checkpoint, để test thì log luôn đọc lại từ đầu
  }
}


filter {
	grok {
		match => {
			"message" => "%{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME:hostname} %{WORD:program}(?:\[%{NUMBER:pid}\])?: %{GREEDYDATA:msg}"
		}
	}

	grok {
		match => {
			"msg" => "Accepted password for %{USERNAME:ssh_user_success} from %{IP:src_ip_success} port %{NUMBER:src_port_success} ssh2"
		}
	}
	grok {
		match => {
			"msg" => "Failed password for %{USERNAME:ssh_user_fail} from %{IP:src_ip_fail} port %{NUMBER:src_port_fail} ssh2"
		}
	}
	
}


#output {
#	stdout { codec => rubydebug } # in ra terminal để test
#}

output {
	elasticsearch {
		hosts => ["https://elk.bhnam-elk.com:9200"]
		#user => ""
		#password =>
		api_key => ":"
		cacert => ""
		index => "test-%{+YYYY.MM.dd}"
		ilm_enabled => false
		manage_template => false
		ssl => true
	}
	stdout { codec => rubydebug }
}

