input {
  file {
    path => "/var/log/auth.log"        # Đường dẫn log cần đọc
	#path => "/etc/logstash/dump/0_logs.txt"
    start_position => "beginning"      # Đọc từ đầu file (nếu để "end" thì chỉ đọc log mới ghi thêm)
    sincedb_path => "/dev/null"        # Bỏ qua checkpoint, để test thì log luôn đọc lại từ đầu
  }
}


filter {
	grok {
		match => {
			#analysis collect logs
			"message" => "%{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME:hostname} %{SYSLOGPROG:program}\[%{NUMBER:pid}\]: %{GREEDYDATA:ssh_msg}"   
			#field: timestamp, hostname,program, pid, ssh_msg
		}
		tag_on_failure => ["_grokfail_ssh"]
	}
	
	if [program] == "sshd" {
		aggregate {
			task_id => "%{pid}"  #gop follow pid
			code => "
				map['timestamp'] ||= event.get('timestamp')
				map['hostname'] ||= event.get('hostname')
				map['pid'] ||= event.get('pid')		
				map['program'] ||= 'sshd'
				map['details'] ||= []
				
				map['details'] << event.get('ssh_msg')
					
				if event.get('ssh_msg') =~ /Accepted password for/
					map['user']      = event.get('ssh_msg').match(/Accepted password for (\S+)/)[1] rescue nil
					map['src_ip']    = event.get('ssh_msg').match(/from ([0-9.]+)/)[1] rescue nil
					map['src_port']  = event.get('ssh_msg').match(/port (\d+)/)[1] rescue nil
					map['auth_method'] = 'password'
				elsif event.get('ssh_msg') =~ /Failed password for/
					map['user']      = event.get('ssh_msg').match(/Failed password for (?:invalid user )?(\S+)/)[1] rescue nil
					map['src_ip']    = event.get('ssh_msg').match(/from ([0-9.]+)/)[1] rescue nil
					map['src_port']  = event.get('ssh_msg').match(/port (\d+)/)[1] rescue nil
					map['status']    = 'failed'
				elsif event.get('ssh_msg') =~ /Invalid user/
					map['user']      = event.get('ssh_msg').match(/Invalid user (\S+)/)[1] rescue nil
					map['src_ip']    = event.get('ssh_msg').match(/from ([0-9.]+)/)[1] rescue nil
					map['src_port']  = event.get('ssh_msg').match(/port (\d+)/)[1] rescue nil
					map['status']    = 'invalid_user'
				else
					map['status']    = 'unknown'
				end

				map['status'] ||= 'unknown'

				if map['details'].any? { |d| d =~ /Invalid user/ } || map['details'].any? { |d| d =~ /user unknown/ }
					map['status'] = 'failed_invalid_user'

				elsif map['details'].any? { |d| d =~ /authentication failure/ } || map['details'].any? { |d| d =~ /Failed password/ }
					map['status'] = 'failed_password'

				elsif map['details'].any? { |d| d =~ /Accepted password/ } 
					map['status'] = 'success_opened'
					if map['details'].any? { |d| d =~ /session closed/ } && map['details'].any? { |d| d =~ /session opened/ }
						map['status'] = 'success_closed'
					else
						map['status'] = 'success_opened'
					end

				elsif map['details'].any? { |d| d =~ /Received disconnect/ } || map['details'].any? { |d| d =~ /Disconnected from/ }
					map['status'] = 'disconnect'

				elsif map['details'].any? { |d| d =~ /Server listening/ }
					map['status'] = 'listening'

				else
					map['status'] = 'unknown'
				end


				
				
			"
			push_map_as_event_on_timeout => true
			timeout_task_id_field => "pid"
			timeout => 30
			
			
			
		}
	
	}
	
}


#output {
#	stdout { codec => rubydebug } # in ra terminal để test
#}

output {
	elasticsearch {
		hosts => [""]
		#user => ""
		#password =>
		api_key => ":"
		cacert => ""
		index => "test-v2-%{+YYYY.MM.dd}"
		ilm_enabled => false
		manage_template => false
		ssl => true
	}
	stdout { codec => rubydebug }
}

