input {
	file {
		path => "/var/log/fail2ban.log"
		start_position => "end"
		tags => ["elk-fail2ban"]
	}

	beats {
		port => 3334
		ssl => true
		ssl_certificate => "/etc/logstash/certs/elk-logstash/elk-logstash.crt"
		ssl_key => "/etc/logstash/certs/elk-logstash/elk-logstash.key"
		tags => ["kibana-fail2ban"]
	}
}

filter {
	grok {
		match => {
			"message" => "%{TIMESTAMP_ISO8601:time} +%{DATA:service} +\[%{NUMBER:pid}\]: +%{LOGLEVEL:loglevel} +%{GREEDYDATA:log_message}"
		}		
	}
}

output {
	elasticsearch {
		hosts => ["https://elk.bhnam-elk.com:9200"]
		#api_key => ":"
		
		api_key => "xlse05kByh5n5AzE9kxM:M-gYcQnOoZbVJMsQofmWSg"
		cacert => "/etc/logstash/certs/ca/ca.crt"
		data_stream => true
		data_stream_type => "logs"
		data_stream_dataset => "fail2ban"
		data_stream_namespace => "default"
		
		#index => "test-fail2ban-%{+YYYY.MM.dd}"
		#ilm_enabled => false
		#manage_template => false
		
		
		ssl => true
	}

	stdout { codec => rubydebug }
}