input {
	file {
		path => "/etc/logstash/dump/fail2ban.txt"
		start_position => "beginning"
		sincedb_path => "/dev/null"
	}
}




filter {
	grok {
		match => {
			"message" => "%{TIMESTAMP_ISO8601:time} +%{DATA:service} +\[%{NUMBER:pid}\]: +%{LOGLEVEL:loglevel} +%{GREEDYDATA:log_message}"
		}		
	}
	
	
}








output {
	elasticsearch {
		hosts => ["https://elk.bhnam-elk.com:9200"]
		#api_key => "715CTZkBQHNx0NCuIG_T:vd16zhowKqe2jQekfE3uhA"
		
		api_key => ":"
		cacert => "/etc/logstash/certs/ca/ca.crt"
		#data_stream => true
		#data_stream_type => "logs"
		#data_stream_dataset => "fail2ban"
		#data_stream_namespace => "default"
		
		index => "test-fail2ban-%{+YYYY.MM.dd}"
		ilm_enabled => false
		manage_template => false
		
		
		ssl => true
	}

	stdout { codec => rubydebug }
}