input {
	beats {
		port => 3300
		ssl => true
		ssl_certificate => "/etc/logstash/certs/elk-logstash/elk-logstash.crt"
		ssl_key => "/etc/logstash/certs/elk-logstash/elk-logstash.key"
	}
}

filter {
	if [agent][type] == "journalbeat" and [syslog][identifier] == "sshd" {
		# --- Dạng 1: Failed / Accepted password ---
		grok {
			match => {
				"message" => [
				"^%{WORD:action} password for %{USER:user_ssh} from %{IP:src_ip} port %{NUMBER:src_port} ssh2",
				"^%{WORD:action} password for invalid user %{USER:user_ssh} from %{IP:src_ip} port %{NUMBER:src_port} ssh2"
				
				
				]
			}
			tag_on_failure => ["_grok_failed_ssh"]
		}
		# --- Chuẩn hoá lại giá trị ---
		mutate {
			add_field => { "event_type" => "ssh_auth" }
			lowercase => ["action"]
		}

		# --- Gán outcome (thành công / thất bại) ---
		if [action] == "failed" {
			mutate { add_field => { "outcome" => "failure" } }
		} else if [action] == "accepted" {
			mutate { add_field => { "outcome" => "success" } }
		}
	}
}



output {
	stdout {
		codec => rubydebug
	}
	file {
		path => "/etc/logstash/dump/ssh-journalbeat-proxmox.log"
		codec => rubydebug
	}
	
}





